Ligum-Roller/Models/Roller.cs
using CsvHelper.Configuration.Attributes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Ligum_Roller.Models
{
	public class Roller
	{
		public DateTime? Timestamp { get; set; }
		public string Barcode { get; set; }
		public IEnumerable<Measurement> Measurements { get; set; }
	}
}

Ligum-Roller/Pages/Date.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ligum_Roller.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
    public class DateModel : PageModel
    {
        public IList<string> Records { get; set; }
        [BindProperty]
        public IFormFile FileUpload { get; set; }
        public string Id { get; set; }
        private readonly ILogger _logger;

        public DateModel(ILogger<DateModel> logger)
		{
            _logger = logger;
        }

        public void OnGet(string id)
        {
            Id = id;
            if (!string.IsNullOrEmpty(Id))
			{
                Records = DataLayer.GetRecordsByDate(Id);
			}
            else
			{
                Records = DataLayer.GetAllRecords();
            }
        }

        public async Task<IActionResult> OnPostUpload()
        {
            _logger.LogInformation("Data file uploaded manually");
            var timestamp = DataLayer.GetCurrentDateTimeStr();
            using (var memoryStream = new MemoryStream())
            {
                await FileUpload.CopyToAsync(memoryStream);
                memoryStream.Position = 0;
                // Upload the file if less than 2 MB
                if (memoryStream.Length < 2097152)
                {
                    using var reader = new StreamReader(memoryStream);
                    var stringData = await reader.ReadToEndAsync();
                    var roller = DataLayer.ParseCsv(stringData);
                    if (roller != null)
					{
                        var id = timestamp + "~" + roller.Barcode;
                        await DataLayer.SaveRecord(stringData, id, _logger);
                    }
                    else
					{
                        _logger.LogError("Wrong format of data");
                    }
                }
            }
            return RedirectToPage("./Index");
        }
    }
}

Ligum-Roller/Pages/DeleteAllRecords.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
    public class DeleteAllRecordsModel : PageModel
    {
        private readonly ILogger _logger;

        public DeleteAllRecordsModel(ILogger<DeleteRecordModel> logger)
		{
            _logger = logger;
        }

        public void OnGet()
        {
        }

        public IActionResult OnPost()
        {
            DataLayer.RemoveAllRecords();
            _logger.LogInformation("Deleted all records");
            return RedirectToPage("./Index");
        }
    }
}

Ligum-Roller/Pages/DeleteRecord.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
    public class DeleteRecordModel : PageModel
    {
        private readonly ILogger _logger;

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }
        public DateTime? Timestamp { get; set; }
        public string Barcode { get; set; }

        public DeleteRecordModel(ILogger<DeleteRecordModel> logger)
		{
            _logger = logger;
		}

        public async Task<IActionResult> OnGet()
        {
            if (string.IsNullOrEmpty(Id))
            {
                return NotFound();
            }
            string data = await DataLayer.ReadRecord(Id);
            if (data == null)
            {
                return NotFound();
            }
            Barcode = DataLayer.ParseCsvBarcode(data);
            Timestamp = DataLayer.ParseDateTime(Id.Split("~")[0]);
            return Page();
        }

        public IActionResult OnPost()
		{
            DataLayer.RemoveRecord(Id);
            _logger.LogInformation("Deleted record {id}", Id);
            return RedirectToPage("./Index");
        }
    }
}

Ligum-Roller/Pages/DeleteRecordsByDate.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
    public class DeleteRecordsByDateModel : PageModel
    {
        private readonly ILogger _logger;

        [BindProperty(SupportsGet = true)]
        public string Id { get; set; }

        public DeleteRecordsByDateModel(ILogger<DeleteRecordsByDateModel> logger)
        {
            _logger = logger;
        }

        public IActionResult OnGet()
        {
            if (string.IsNullOrEmpty(Id))
            {
                return NotFound();
            }
            return Page();
        }

        public IActionResult OnPost()
        {
            DataLayer.RemoveRecordsByDate(Id);
            _logger.LogInformation("Deleted all records from date " + Id);
            return RedirectToPage("./Index");
        }
    }
}

Ligum-Roller/Pages/Index.cshtml.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Threading.Tasks;
using Ligum_Roller.Controllers;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
    public class IndexModel : PageModel
    {
        public IList<string> Records { get; set; }
        [BindProperty]
        public IFormFile FileUpload { get; set; }
        private readonly ILogger _logger;

        public IndexModel(ILogger<IndexModel> logger)
		{
            _logger = logger;
        }

        public void OnGet()
        {
            Records = DataLayer.GetAllRecords();
        }

        public async Task<IActionResult> OnPostUpload()
        {
            _logger.LogInformation("Data file uploaded manually");
            var timestamp = DataLayer.GetCurrentDateTimeStr();
            using (var memoryStream = new MemoryStream())
            {
                await FileUpload.CopyToAsync(memoryStream);
                memoryStream.Position = 0;
                // Upload the file if less than 2 MB
                if (memoryStream.Length < 2097152)
                {
                    using var reader = new StreamReader(memoryStream);
                    var stringData = await reader.ReadToEndAsync();
                    var roller = DataLayer.ParseCsv(stringData);
                    if (roller != null)
					{
                        var id = timestamp + "~" + roller.Barcode;
                        await DataLayer.SaveRecord(stringData, id, _logger);
                    }
                    else
					{
                        _logger.LogError("Wrong format of data");
                    }
                }
            }
            return RedirectToPage("./Index");
        }
    }
}

Ligum-Roller/Pages/Privacy.cshtml.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Microsoft.Extensions.Logging;

namespace Ligum_Roller.Pages
{
	public class PrivacyModel : PageModel
	{
		private readonly ILogger<PrivacyModel> _logger;

		public PrivacyModel(ILogger<PrivacyModel> logger)
		{
			_logger = logger;
		}

		public void OnGet()
		{
		}
	}
}

Ligum-Roller/Pages/Roller.cshtml.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Text.RegularExpressions;
using System.Threading.Tasks;
using Ligum_Roller.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using Wkhtmltopdf.NetCore;

namespace Ligum_Roller.Pages
{
	public class RollerModel : PageModel
	{
		public Roller Roller { get; set; }
		[BindProperty(SupportsGet = true)]
		public string Id { get; set; }
		[BindProperty(SupportsGet = true), StringLength(1000)]
		public string SearchString { get; set; }

		public RollerModel()
		{
		}

		public async Task<IActionResult> OnGet()
		{
			if (string.IsNullOrEmpty(Id))
			{
				return NotFound();
			}
			string data = await DataLayer.ReadRecord(Id);
			if (data == null)
			{
				return NotFound();
			}
			Roller = DataLayer.ParseCsv(data);
			if (Roller == null)
			{
				return StatusCode(500);
			}
			Roller.Timestamp = DataLayer.ParseDateTime(Id.Split("~")[0]);

			if (!string.IsNullOrEmpty(SearchString) && Roller.Measurements != null)
			{
				// comma separated decimal values
				var decNumRegex = @"[+-]?([0-9]*[.])?[0-9]+";
				var regex = String.Format(@"^({0})+(,*{0})*,*$", decNumRegex);
				SearchString = Regex.Replace(SearchString, @"\s", ""); // remove whitespaces
				if (Regex.Match(SearchString, regex).Success)
				{
					var searchNums = SearchString.Split(',')
						.Where(n => !string.IsNullOrEmpty(n))
						.Select(n => (int)double.Parse(n))
						.ToList();
					Roller.Measurements = Roller.Measurements
						.Where(m => searchNums.Exists(n => ((int)m.Distance).Equals(n)))
						.ToList();
				}
			}
			return Page();
		}

		public async Task<FileResult> OnGetDownloadCsv()
		{
			var dataBytes = await DataLayer.ReadRecordBytes(Id);
			return File(dataBytes, "application/octet-stream", Id + ".csv");
		}
	}
}

Ligum-Roller/Pages/ConfigPdf.cshtml
@page
@model Ligum_Roller.Pages.ConfigPdfModel
@{
	var globalConfig = Model.GlobalConfig;
	var formAction = (!globalConfig) ? "/GeneratePdf?id=" + Model.Id : "";
}

<link href="./css/pdf.css" rel="stylesheet">

@if (Model.Success)
{
	<div class="alert alert-success alert-dismissible">
		Formát protokolu bol úspešne uložený.
	</div>
}
@if (globalConfig)
{
	<h3>Formát protokolu:</h3>
}
else
{
	<h3>Protokol:</h3>
}
<form action="@formAction" method="post" target="@((globalConfig) ? "_self" : "_blank")">
	<table class="tg">
		<tbody>
			<tr>
				<td class="tg-value" colspan="6" style="text-align: center">
					@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.CompanyName))
					{
						<input asp-for="PdfConfig.CompanyName" class="p-text" style="float:left; font-weight: bold;" />
					}
					else
					{
						<p class="p-text" style="float:left; font-weight:bold;">@Model.PdfConfig.CompanyName</p>
						<input asp-for="PdfConfig.CompanyName" class="p-text" style="float:left; font-weight: bold;" hidden />
					}
					@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Title))
					{
						<input asp-for="PdfConfig.Title" class="p-text" style="display: inline-block; font-size:medium;" />
					}
					else
					{
						<p class="p-text" style="display: inline-block; font-size:medium">@Model.PdfConfig.Title</p>
						<input asp-for="PdfConfig.Title" class="p-text" style="display: inline-block; font-size:medium;" hidden />
					}
					<p class="p-text" style="float:right;">@Model.Roller.Timestamp</p>
				</td>
			</tr>
			<tr>
				<td class="tg-name">Kód produktu:</td>
				@if (globalConfig)
				{
					<td class="tg-value">@Model.Roller.Barcode</td>
				}
				else
				{
					<td class="tg-value"><input asp-for="PdfConfig.Barcode" /></td>
				}
				<td class="tg-empty"></td>
				@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Property1.Name))
				{
					<td class="tg-name"><input asp-for="PdfConfig.Property1.Name" class="bold-input" /></td>
				}
				else
				{
					<td class="tg-name">@Model.PdfConfig.Property1.Name<input asp-for="PdfConfig.Property1.Name" class="bold-input" hidden /></td>
				}
				<td class="tg-value"><input asp-for="PdfConfig.Property1.Value" /></td>
				<td class="tg-logo" rowspan="3"><img id="logo" src="./logo.png" /></td>
			</tr>
			<tr>
				@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Property2.Name))
				{
					<td class="tg-name"><input asp-for="PdfConfig.Property2.Name" class="bold-input" /></td>
				}
				else
				{
					<td class="tg-name">@Model.PdfConfig.Property2.Name<input asp-for="PdfConfig.Property2.Name" class="bold-input" hidden /></td>
				}
				<td class="tg-value"><input asp-for="PdfConfig.Property2.Value" /></td>
				<td class="tg-empty"></td>
				@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Property3.Name))
				{
					<td class="tg-name"><input asp-for="PdfConfig.Property3.Name" class="bold-input" /></td>
				}
				else
				{
					<td class="tg-name">@Model.PdfConfig.Property3.Name<input asp-for="PdfConfig.Property3.Name" class="bold-input" hidden /></td>
				}
				<td class="tg-value"><input asp-for="PdfConfig.Property3.Value" /></td>
			</tr>
			<tr>
				@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Property4.Name))
				{
					<td class="tg-name"><input asp-for="PdfConfig.Property4.Name" class="bold-input" /></td>
				}
				else
				{
					<td class="tg-name">@Model.PdfConfig.Property4.Name<input asp-for="PdfConfig.Property4.Name" class="bold-input" hidden /></td>
				}
				<td class="tg-value"><input asp-for="PdfConfig.Property4.Value" /></td>
				<td class="tg-empty"></td>
				@if (globalConfig || String.IsNullOrEmpty(Model.PdfConfig.Property5.Name))
				{
					<td class="tg-name"><input asp-for="PdfConfig.Property5.Name" class="bold-input" /></td>
				}
				else
				{
					<td class="tg-name">@Model.PdfConfig.Property5.Name<input asp-for="PdfConfig.Property5.Name" class="bold-input" hidden /></td>
				}
				<td class="tg-value"><input asp-for="PdfConfig.Property5.Value" /></td>
			</tr>

		</tbody>
	</table>

	<hr class="hr">

	<p>
		Počet hodnôt v tabuľke:
		<input asp-for="PdfConfig.NumValues" />
		<span asp-validation-for="PdfConfig.NumValues" class="text-danger"></span>
	</p>

	<div style="float:right">
		@if (globalConfig)
		{
			<a class="btn btn-secondary" asp-page="./Index">Späť</a>
			<input type="submit" value="Uložiť formát" class="btn btn-primary" />
		}
		else
		{
			<a class="btn btn-secondary" href="/Roller?id=@Model.Id">Späť</a>
			<input type="submit" value="Vygenerovať protokol" class="btn btn-primary" target="_blank" />
		}
	</div>
</form>

@section Scripts {
	@{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Ligum-Roller/Pages/Date.cshtml
@page
@model DateModel
@{ 
	DateTime? itemDateTime;
}

<form asp-page-handler="Upload" method="post" enctype="multipart/form-data">
	<p style="margin-bottom: 1rem;">
		<a class="btn btn-secondary" asp-page="./Index">Zobraziť merania podľa dátumov</a>
		<input type="file" asp-for="FileUpload" id="selectedFile" style="display: none;" onchange="this.form.submit()" />
		<input type="button" class="btn btn-link" value="Nahrať súbor" onclick="document.getElementById('selectedFile').click();" />
	</p>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				Merania
			</th>
			<th>
				Dátum a čas
			</th>
			<th>
				@if (!string.IsNullOrEmpty(Model.Id))
				{
					<a asp-page="./DeleteRecordsByDate" asp-route-id="@Model.Id">Zmazať všetko</a>

				}
				else
				{
					<a asp-page="./DeleteAllRecords">Zmazať všetko</a>
				}
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Records != null)
		@foreach (var item in Model.Records)
		{
		<tr>
			<td>
				@{
					var data = item.Split("~");
					var timeDate = data[0];
					var barcode = (data.Length > 1) ? data[1] : "";
					if ((itemDateTime = DataLayer.ParseDateTime(timeDate)) != null)
					{
						var showedValue = (!string.IsNullOrEmpty(barcode)) ? barcode : itemDateTime.ToString();
						<a asp-page="./Roller" asp-route-id="@item">
							<img src="~/csv_icon.png" alt="icon" width="50" height="50" style="margin-right: 10px">
							@showedValue 
						</a>
					}
				}
			</td>
			<td class="text-center-vertical">
				<a style="color: black;" asp-page="./Roller" asp-route-id="@item">@itemDateTime</a>
			</td>
			<td class="text-center-vertical">
				<a asp-page="./DeleteRecord" asp-route-id="@item">Zmazať</a>
			</td>
		</tr>
		}
	</tbody>
</table>

Ligum-Roller/Pages/DeleteAllRecords.cshtml
@page
@model Ligum_Roller.Pages.DeleteAllRecordsModel
@{
}

<h3>Ste si istý, že chcete zmazať všetky merania?</h3>
<div>
	<hr />

	<form method="post">
		<input type="submit" value="Zmazať" class="btn btn-danger" />
		<a class="btn btn-secondary" asp-page="./Index">Späť na všetky merania</a>
	</form>
</div>

Ligum-Roller/Pages/DeleteRecord.cshtml
@page
@model Ligum_Roller.Pages.DeleteRecordModel
@{
}

<h3>Ste si istý, že chcete zmazať toto meranie?</h3>
<div>
	<h4>Kód: @Model.Barcode</h4>
	<hr />
	<div>
		<img src="~/csv_icon.png" alt="icon" width="50" height="50" style="margin-right: 10px">
		@Model.Timestamp
	</div>
	<hr />

	<form method="post">
		<input type="hidden" asp-for="@Model.Id" />
		<input type="submit" value="Zmazať" class="btn btn-danger" />
		<a class="btn btn-secondary" href="@Request.Headers["Referer"].ToString()">Vrátiť sa späť</a>
	</form>
</div>

Ligum-Roller/Pages/DeleteRecordsByDate.cshtml
@page
@model Ligum_Roller.Pages.DeleteRecordsByDateModel
@{
}

<h3>Ste si istý, že chcete zmazať všetky merania z tohto dátumu?</h3>
<div>
	<h4>Dátum: @Model.Id</h4>
	<hr />

	<form method="post">
		<input type="submit" value="Zmazať" class="btn btn-danger" />
		<a class="btn btn-secondary" href="@Request.Headers["Referer"].ToString()">Vrátiť sa späť</a>
	</form>
</div>

Ligum-Roller/Pages/Index.cshtml
@page
@model Ligum_Roller.Pages.IndexModel
@{
}

<form asp-page-handler="Upload" method="post" enctype="multipart/form-data">
	<p style="margin-bottom: 1rem;">
		<a class="btn btn-secondary" asp-page="./Date">Zobraziť jednotlivé merania</a>
		<input type="file" asp-for="FileUpload" id="selectedFile" style="display: none;" onchange="this.form.submit()" />
		<input type="button" class="btn btn-link" value="Nahrať súbor" onclick="document.getElementById('selectedFile').click();" />
	</p>
</form>

<table class="table">
	<thead>
		<tr>
			<th>
				Dátum
			</th>
			<th>
				<a asp-page="./DeleteAllRecords">Zmazať všetko</a>
			</th>
			<th></th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Records != null)
			@foreach (var item in Model.Records)
			{
				<tr>
					<td>
						<a asp-page="./Date" asp-route-id="@item">
							<img src="~/folder_icon.png" alt="icon" width="50" height="50" style="margin-right: 10px">
							@item
						</a>
					</td>
					<td class="text-center-vertical">
						<a asp-page="./DeleteRecordsByDate" asp-route-id="@item">Zmazať</a>
					</td>
				</tr>
			}
	</tbody>
</table>

Ligum-Roller/Pages/Roller.cshtml
@page
@model RollerModel

<div class="text-center">
	<h1 class="">Kód: @Model.Roller.Barcode</h1>
	<h2 class="">@Model.Roller.Timestamp</h2>
</div>

<hr class="blank-hr">

<form asp-route-id="@Model.Id" method="get">
	<div class="form-actions no-color">
		<input type="hidden" asp-for="Id" />
		<p class="text-center">
			<a class="btn btn-secondary" asp-page="./Index">Späť na všetky merania</a>
			<a asp-page="./ConfigPdf" asp-route-id="@Model.Id" class="btn btn-success" style="width: 200px;">Vygenerovať protokol</a>
			<a href="graph/@(Model.Id).png" class="btn btn-info" target="_blank">Zobraziť graf</a>
			<a asp-page-handler="DownloadCsv" asp-route-id="@Model.Id" class="btn btn-info">Uložiť ako CSV</a>
			<a asp-page="./DeleteRecord" asp-route-id="@Model.Id" class="btn btn-danger">Zmazať</a>
		</p>
		<hr />
		<p>
			Vzdialenosti:
			<input id="searchInput" type="text" name="SearchString" value="@Model.SearchString" placeholder="Čísla oddelené čiarkou" size="50" />
			<span id="searchClear">&#x2715;</span>
			<input type="submit" value="Hľadať" class="btn btn-primary" />
		</p>
	</div>
</form>

<table class="table">
	<thead>
		<tr>
			<th class="text-center">
				Vzdiaľenosť (mm)
			</th>
			<th>
				Priemer (mm)
			</th>
		</tr>
	</thead>
	<tbody>
		@if (Model.Roller.Measurements != null)
			@foreach (var item in Model.Roller.Measurements)
			{
				<tr>
					<td class="text-center">
						@((int)item.Distance)
					</td>
					<td>
						@String.Format("{0:0.000}", item.Diameter)
					</td>
				</tr>
			}
	</tbody>
</table>